permissions:
  contents: write

name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag to release (e.g. 0.0.1-beta)'
        required: true
      skip_integration_tests:
        description: 'Skip integration tests?'
        required: false
        default: 'false'
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Run unit tests
      run: mvn test

    - name: Install Google Chrome
      if: ${{ !github.event.inputs.skip_integration_tests }}
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run integration tests
      if: ${{ !github.event.inputs.skip_integration_tests }}
      run: mvn verify -DskipUTs

    - name: Build Projects
      run: mvn package -DskipITs -DskipUTs

    - name: Build Flattened POM for core
      run: mvn -f bandcamp-scraper-core flatten:flatten -DskipITs

    - name: Rename CLI release artifact
      run: |
        mv bandcamp-scraper-cli/target/bandcamp-scraper-cli-0.0.1-SNAPSHOT.zip \
           bandcamp-scraper-cli/target/bandcamp-scraper-cli-${{ github.event.inputs.release_tag }}.zip

    - name: Rename core release artifacts
      run: |
        mv bandcamp-scraper-core/target/bandcamp-scraper-core-0.0.1-SNAPSHOT.jar \
           bandcamp-scraper-core/target/bandcamp-scraper-core-${{ github.event.inputs.release_tag }}.jar
        mv bandcamp-scraper-core/target/bandcamp-scraper-core-0.0.1-SNAPSHOT-sources.jar \
           bandcamp-scraper-core/target/bandcamp-scraper-core-${{ github.event.inputs.release_tag }}-sources.jar
        mv bandcamp-scraper-core/target/.flattened-pom.xml \
           bandcamp-scraper-core/target/bandcamp-scraper-core-${{ github.event.inputs.release_tag }}.pom

    - name: Create GitHub release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.release_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload CLI release artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: bandcamp-scraper-cli/target/bandcamp-scraper-cli-${{ github.event.inputs.release_tag }}.zip
        asset_name: bandcamp-scraper-cli-${{ github.event.inputs.release_tag }}.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload core release JAR artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: bandcamp-scraper-core/target/bandcamp-scraper-core-${{ github.event.inputs.release_tag }}.jar
        asset_name: bandcamp-scraper-core-${{ github.event.inputs.release_tag }}.jar
        asset_content_type: application/java-archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload core release source JAR artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: bandcamp-scraper-core/target/bandcamp-scraper-core-${{ github.event.inputs.release_tag }}-sources.jar
        asset_name: bandcamp-scraper-core-${{ github.event.inputs.release_tag }}-sources.jar
        asset_content_type: application/java-archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload core release POM artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: bandcamp-scraper-core/target/bandcamp-scraper-core-${{ github.event.inputs.release_tag }}.pom
        asset_name: bandcamp-scraper-core-${{ github.event.inputs.release_tag }}.pom
        asset_content_type: application/xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
